/*
// SELECT LIST BY ID

// list.style.background = 'blue' SELECT LINKS BY TAG NAME

// SELECT LIST USING QUERY SELECTOR

// SELECT PARAGRAPHS BY CLASS NAME

// SELECT PARAGRAPHS BY QUERY SELECTOR MANIPULATE: ADD NEW CLASSNAME TO LINKS

// MANIPULATE: REMOVE NEW CLASSNAME FROM LINKS

// MANIPULATE: TOGGLE CLASS CALLED ACTIVE MANIPULATE: SET LINK ATTRIBUTES TO

// HAVE A RED COLOUR - INLINE STYLE MAKE A NEW DIV DYNAMICALLY
*/